"""Turning a local ROSE defect into something a maintainer can act on.

ROSE makes no network calls, and that guarantee is worth more than the
convenience of filing automatically. So this writes a report to disk and stops.
Whether it ever leaves the machine is the user's decision, taken in the open,
using their own credentials — the agent shows them the file and asks.

What goes in is chosen by what a maintainer actually needs to reproduce a
failure, intersected with what is safe to hand over:

* Counts, kinds and timings of events — enough to see that seven reflections
  ran and captured nothing, which is the whole diagnosis in the case this was
  built for.
* Node ids, which are opaque hashes, and never lesson bodies or titles. A
  lesson is the user's own work and frequently describes their codebase.
* Never prompts, transcripts, file paths inside their project, or repository
  names. The symptom is written by the agent in its own words instead.

Everything still passes through the redactor on the way out, because a
description written in good faith can quote a key.
"""

from __future__ import annotations

import platform
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import __version__
from .redact import redact

ISSUE_URL = "https://github.com/yiheinchai/rose/issues/new"

# Config keys safe to disclose: they shape behaviour and contain no content.
# Anything naming a path, a model or a binary is left out.
SAFE_CONFIG = (
    "agent",
    "recall.strategy",
    "recall.max_pack_tokens",
    "recall.judge_calls",
    "recall.max_depth",
    "learning.nudge_mode",
    "learning.nudge_after_tool_calls",
    "learning.min_surprises",
    "compaction.min_successes",
    "compaction.max_ratio",
    "compaction.threshold",
    "dream.interval_s",
    "dream.min_new_episodes",
    "dream.max_apexes",
)


def _stage_summary(store: Any, days: int) -> list[str]:
    """Per-stage activity, which is what localises a defect to one stage."""
    since = ""
    try:
        cutoff = datetime.now(timezone.utc).timestamp() - days * 86400
        since = datetime.fromtimestamp(cutoff, timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    except Exception:  # pragma: no cover - clock weirdness must not block a report
        pass

    kinds: Counter[str] = Counter()
    captures_by: Counter[str] = Counter()
    for kind in ("inject", "nudge", "capture", "mint", "compaction", "attributed", "conflict"):
        for event in store.read_events(kind, limit=4000):
            if since and str(event.get("ts", "")) < since:
                continue
            kinds[kind] += 1
            if kind == "capture":
                captures_by[str(event.get("by") or "unrecorded")] += 1

    lines = [f"| {k} | {v} |" for k, v in sorted(kinds.items())]
    if captures_by:
        detail = ", ".join(f"{n} by {who}" for who, n in sorted(captures_by.items()))
        lines.append(f"| capture origin | {detail} |")
    return lines


def build(store: Any, symptom: str, *, expected: str = "", days: int = 7) -> str:
    """The report body. Pure — writes nothing, sends nothing."""
    cfg = []
    for key in SAFE_CONFIG:
        try:
            value = store.config.get(key)
        except Exception:
            continue
        if value is not None:
            cfg.append(f"| `{key}` | `{value}` |")

    nodes = sum(1 for _ in store.nodes()) if hasattr(store, "nodes") else 0
    episodes = len(store.episodes()) if hasattr(store, "episodes") else 0

    body = f"""### What went wrong

{redact(symptom.strip()) or "_(not described)_"}

### What I expected instead

{redact(expected.strip()) or "_(not described)_"}

### Environment

| | |
|---|---|
| rose | {__version__} |
| python | {sys.version.split()[0]} |
| platform | {platform.system()} {platform.machine()} |
| store | {nodes} nodes, {episodes} episodes |

### Configuration (non-default keys are the usual culprit)

| key | value |
|---|---|
{chr(10).join(cfg) or "| — | — |"}

### Activity, last {days} day(s)

| event | count |
|---|---|
{chr(10).join(_stage_summary(store, days)) or "| — | — |"}

---

<sub>Generated by `rose report`. It contains counts and settings only — no
lesson text, no prompts, no transcript, no paths from this machine. ROSE did not
send this anywhere; a human chose to.</sub>
"""
    return redact(body)


def write(store: Any, symptom: str, *, expected: str = "", days: int = 7) -> Path:
    """Save the report beside the store and return where it landed."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out = Path(store.root) / "reports" / f"rose-{stamp}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build(store, symptom, expected=expected, days=days), encoding="utf-8")
    return out


def gh_command(path: Path, title: str) -> str:
    """The exact command to file it, for a human or agent to run deliberately."""
    safe = title.replace('"', "'")
    return (
        f'gh issue create --repo yiheinchai/rose \\\n'
        f'  --title "{safe}" \\\n'
        f'  --body-file "{path}"'
    )
